### ISSUE TITLE
Can't list correlated erros with cor.err

### ISSUE THREAD

**Issue by Gangrelino** [murphymv/semEff#42]
I am trying to run a few `betareg` models and I trying to understand what is wrong when I indicate which variables have correlated errors (`cor.err`), particularly when you have multiple variables in a model. Here is an example and output on console:

```
library(dplyr)
library(semEff)

shipley2<-shipley %>% mutate(Growth_perc=Growth/100)

model1<-betareg( Growth_perc  ~   Survival, data=shipley2)

model2<-betareg( Survival ~ year + Date + DD ,data=shipley2)

testing<-bootEff(list(
  model1,
  model2),
  cor.err = c("Growth_perc ~~ year"),
  R = 10)
```
```

#Error in bootEff(list(model1, model2), cor.err = c("Growth_perc ~~ year"),  : 
# Names of variable(s) with correlated errors missing from list of models and/or weights.

```

The problem does not seem to be related to betareg _per se_

**Comment by murphymv** [comment]
Hi,

Sorry for the delayed response, I was away for a couple of weeks recently. 

It looks like you have specified the `corr.err` argument incorrectly - it should be `c("Growth_perc ~~ Survival")`, as those are the names of the response variables with correlated errors. The example above runs fine when that's changed.

Thanks,
Mark
