### ISSUE TITLE
lapply bootEff

### ISSUE THREAD

**Issue by Canderson156** [murphymv/semEff#44]
Hi again,

I'd like to apply the same path model structure to multiple groups, and look at the results using semEff. My strategy has been to use lapply. It doesn't seem to work with bootEff. Do you have any thoughts on how to do this?

data(keeley, package = "piecewiseSEM")
keeley <- as_tibble(keeley) %>%
  mutate(group = sample(c("A", "B"), nrow(keeley), TRUE))

keeley_split <- group_split(keeley, group)

path_structure_keeley <- function(x) {

path <- psem(
  lm(age ~ distance, data = x),
  lm(hetero ~ distance, data = x),
  lm(abiotic ~ distance, data = x),
  lm(firesev ~ age, data = x),
  lm(cover ~ firesev, data = x),
  lm(rich ~ distance + hetero + abiotic + cover, data = x)
)
}

keeley_models <- lapply(keeley_split, path_structure_keeley)

keeley_boot <- lapply(keeley_models, bootEff,  R = 1000)

Error in getData(m) : 
  'data' does not contain all variables used to fit model.

**Comment by murphymv** [comment]
Hi,

When providing code examples, it's good practice to source the packages you are using. There are at least three here that would need to be installed and loaded via a `library()` call for this example to be run on another machine. Alternatively (or additionally), you could load some functions directly via `package::function()`, which can be good to see where things are coming from.

The first thing to note here is that I get a different error message than you:

```
Error in eval(mc$data, env) : object 'x' not found
```

However, proceeding on the basis that this is the issue, or at least the source of the issue... this isn't really a bug in `bootEff()` - it's more of a necessary limitation on how it handles datasets for resampling. Basically, the function needs access to the data object to do resampling and if it can't find it it will throw an error. When models are fit via function that iterates through different datasets, the name of the dataset in the model call becomes `x` or whatever the data argument name is in the function. Then when you try to call `bootEff()` on the output of that function, it can't find `x` anywhere (`x` only existed inside the function environment). To get around this, you could access the `$data` slot helpfully provided in the `psem` objects , e.g.:

```
keeley_boot <- lapply(keeley_models, function(i) {
  bootEff(i, data = i$data, R = 1000)
})
```

If the data objects were not available this way though, you could always just iterate through both the models and the data list:

```
keeley_boot <- lapply(1:length(keeley_models), function(i) {
  m <- keeley_models[[i]]
  d <- keeley_split[[i]]
  bootEff(m, data = d, R = 1000)
})
```

Let me know if that helps.

Cheers,
Mark
