### ISSUE TITLE
"WARNING:All vanes of t1* are NA" - only on one computer when running the same code, also 10x slower

### ISSUE THREAD

**Issue by Canderson156** [murphymv/semEff#45]
Hi again,

I'm having another strange issue with the bootEff function that seems to be localized to computer A, and doesn't occur when the same code is run on computer B. I tried to make a test version of the dataset to illustrate the issue for you here, and interestingly, the code works fine with the shorter test dataset on both computer. The test dataset has 100 rows of the full dataset, and I removed some of the columns. In my previous issue, the bug was due to a column I wasn't calling in the function, so I wonder if perhaps this is a similar bug.

When the bootEff function is run with test dataset is run on either computer, or with the full dataset on computer A, the results for bootEff make sense. For example:

#t1* -0.00000000000002290888  0.00000000000002787414 0.00000000000000501701
#t2* -0.60260267367821596096  0.00415074893531663935 0.03539173696975370098
#t3*  0.16633473320324301814 -0.00470021776430315508 0.04867780856680303803
#t4*  0.55316550100493566688 -0.00822456537248661412 0.03631034514791206536

When the boot Eff function is run with the full dataset on computer B, there is a warning for all variables in the model:

Bootstrap statistics:
WARNING: All values of t1* are NA

Also, when I tested with the full dataset, computer A took 56 mins to run 100 iteration, while computer B took 6 mins. The test dataset takes about 50 seconds on both computers

Because I can't share the full dataset here, I'll share the script and associated data here:

 https://drive.google.com/drive/folders/13xM9x7BcP2MwApEjSdRMmlN4i3WOYqcn?usp=sharing

**Computer A session info:**

R version 4.0.3 (2020-10-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252  

About your PC
Processor: Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz 3.51 GHz
Installed RAM: 80.0GB

**Computer B session info:** 

> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8    LC_MONETARY=English_Canada.utf8 LC_NUMERIC=C                    LC_TIME=English_Canada.utf8    

About your PC: Not available due to administrative controls....

**Comment by murphymv** [comment]
Hi, I wasn't able to replicate this issue with the information available so I'm not sure whats going on sorry. I've closed it for now but let me know if you're still getting problems.
