### ISSUE TITLE
Error message "estimated adjustment 'a' is NA"

### ISSUE THREAD

**Issue by JochemKail** [murphymv/semEff#46]
Dear Murphy, dear semEff users,

I found out myself that this was a stupid question and the solution is very easy: 

I found out that the error message comes from the build in function boot::boot.ci. When using type="bca", this error occurs because bias-corrected, accelerated confidence interval calculation is unstable for a small number of replicates. The error no longer occurred when I used >= 1000 replicates. Finally, I think about choosing type="perc", because it is conceptually much more simple and straightforward. 

Nevertheless, I did not delete the question, because somebody else might come across the same issue. However, I am also happy to delete it.

The original questions was the following:
Dear Murphy,
first of all many thanks for developing the semEff package. We had a hard time in the past calculating indirect and direct effects based on the output of piecewiseSEM::psem.

I have just downloaded semEff yesterday. I set up a piecewiseSEM::psem and the summary gives reasonable results for the standard estimates (path coefficients).

I then used semEff to bootstrap the path coefficients. However, when I try to use this bootEff object as an input for semEff, I get the following error message: "Error in bca.ci(boot.out, conf, index[1L], L = L, t = t.o, t0 = t0.o,  : estimated adjustment 'a' is NA".

I tried to understand where this error comes from but was not able to do so. 

Do you have any idea what might be wrong. See the code and data attached below. Please do not hesitate to contact me if you need any further information!

Many thanks

Jochem

Code:
#SEM package
library(piecewiseSEM)
#semEFF to calculate direct, indirect and total effects of variables in the SEM
library(semEff)

#GLMs
GLMTNFull3GaussTrans <- glm(TN_mgl ~ B10_Agri + B10_Urban, family = gaussian(link = "identity"), data=dfsitesGLMTrans)
GLMTPFull3GaussTrans <- glm(TP_mgl ~ B10_Agri + B10_Urban, family = gaussian(link = "identity"), data=dfsitesGLMTrans)
GLMChlaFull3GaussTrans <- glm(Chla_mcgl ~ TN_mgl + TP_mgl, family = gaussian(link = "identity"), data=dfsitesGLMTrans)
GLMMPAllFull3GaussTrans <- glm(MP_EQR01 ~ Chla_mcgl + TN_mgl + TP_mgl + B10_Agri + B10_Urban + LakeScore , family = gaussian(link = "identity"), data=dfsitesGLMTrans)

#SEM and evaluation
SEMAllFull3GaussTrans <- psem(GLMTNFull3GaussTrans, GLMTPFull3GaussTrans, GLMChlaFull3GaussTrans, GLMMPAllFull3GaussTrans, TN_mgl %~~% TP_mgl) 
summary(SEMAllFull3GaussTrans, .progressBar = F, conserve = T)

#Some diagnostics on the path coefficients from the piecewiseSEM package
coefs(SEMAllFull3GaussTrans) # path coefficients
plot(SEMAllFull3GaussTrans, alpha=0.05)
rsquared(SEMAllFull3GaussTrans, method = "trigamma")

#Calculate direct, indirect and total effect using the new package semEff!, which allows to do a bootstrapping first for the path coefficients to finally get confidence intervals!
SEM3Boot <- bootEff(SEMAllFull3GaussTrans, 10, seed=12345) #bootstrap the coefficients of the SEM first
summary(SEM3Boot)
View(SEM3Boot)

SEM3Eff <- semEff(SEM3Boot, predictors = NULL, mediators = NULL, use.raw = FALSE, ci.conf = 0.95, ci.type = "bca", digits = 3, bci.arg=NULL)

[dfsitesGLMTrans.txt](https://github.com/murphymv/semEff/files/10236231/dfsitesGLMTrans.txt)

**Comment by murphymv** [comment]
Closed, as error originated from `boot::bootci()` and can be solved with increased bootstrap replicates or by selecting a different interval calculation method. Thanks for posting the question and for using the package.

Mark
