### ISSUE TITLE
getData does not work

### ISSUE THREAD

**Issue by BrexLed** [murphymv/semEff#5]
Dear Mark V. Murphy,
I am trying to bootstrap some CI using the semEff pkg.

I created an piecewiseSEM object and then I used the semEff function.
It looks there is a little issue with the getData function, what do you think?

![Cattura](https://user-images.githubusercontent.com/47738882/82318513-49492880-99d0-11ea-83a9-bb983a132a83.PNG)

edit 1:
I also tried
bootEff(fit, ran.eff="random effect") 
but the error is the same.

Thank you in advance

edit 2: I solved in this way

_fit_ <- psem(  
    lmer( Y ~ X + M + (1|groupe_recode),
        na.action = na.omit, data = dati) 
)
summary(_fit_)

**fitB** <- list(  
    lmer( Y ~ **-1** + X + M+ (1|groupe_recode),
        na.action = na.omit, data = dati) 
)

A=bootEff(**fitB**, ran.eff="groupe_recode", 
          type="perc", ncpu=3, R=1000)
CI=bootCI(A)

**Comment by murphymv** [comment]
Hi, many apologies that I missed this issue from a few months ago! I see you solved it yourself anyway - `semEff` doesn't currently support `psem` objects. This is easy to work around as those objects are created from a list of models anyway, so just supply the list of models instead.
