### ISSUE TITLE
summary(semEff(sem.Eff.boot)) output to matrix/dataframe

### ISSUE THREAD

**Issue by mvedrin** [murphymv/semEff#51]
Hi there, 

First of all thanks so much for this package - it has helped so much with my work on mixed effects multiple regression / sem modeling.

I am wondering if there is some way of converting the summary(semEff(sem.Eff.boot)) output from the text based tables into a matrix or dataframe format?

I was trying to look through the model object components to extract all of the numbers myself and put into a dataframe, but have been having trouble locating them. I am referring to the Effect, Bias, Std. Err., Lower CI, and Upper CI summary output. For example, this output I have been trying to get into a dataframe format:
![image](https://github.com/murphymv/semEff/assets/97481432/e7ab5f92-35c3-4232-9131-6380b4bbb634)

Thanks for any help!

**Comment by murphymv** [comment]
Hi,

Thanks for your feedback and for using the package.

This is similar to a [previous request](https://github.com/murphymv/semEff/issues/38#issue-1165494164), and there is some helpful code there which might get you what you want. I haven't incorporated that functionality in the package at least as yet, but might do so in the next version.

Cheers,
Mark

**Comment by mvedrin** [comment]
Hey Mark,

Ah okay thanks for pointing me to that previous request and the code they provided. I didn't see that in the pages, I'm newer to github so maybe I didn't look in the right place!

Best,
Matt

**Comment by murphymv** [comment]
Hi,

Just to update - this functionality is now available in the latest version of the package (0.7.0), via the function `getEffTable()`. If the package is not yet on CRAN, you can test things out with the latest dev version from here.

Cheers,
Mark
